language: node_js
node_js:
- node
env:
  global:
    secure: mQ+nJc9KqW2/rNR50lBpF+PV5Wxti006hQsi2qEHKU5bVCh2SdxR6MQNkuMSUYlr9xobNX4YG9i5G/d7PAclOBM9aePKC9in32MbMUgB8nM4/iKgf0v9tYnTOWSMWzBbOH+ZiyniWo5VAelvNm3qeQrGwrBf1INd8GEqGgXtY6s=
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y tinyproxy
